### ISSUE TITLE
Complete implementation of /types endpoints in API

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#119]

**Comment by pooja1pathak** [comment]
Hi @taliaga @c0c0n3 I want to contribute for this issue. Please assign it to me.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak, thanks for taking care of this!

I've just had a look at the code, it looks like it'd be best to implement a separate query in the translator rather than adding to the existing one. This will help going forward if we ever get around to replacing the string based query building with an AST based approach.

Thanks!

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 I have implemented the code using query method in translator/crate.py. The code is working as per our requirement.

As per your comment https://github.com/smartsdk/ngsi-timeseries-api/issues/119#issuecomment-582796854 , I tried to build a new query method but unable to get the perfect query. I am still working on that.

I just wanted to know about your expectation from separate query, as same method is used on all other APIs. Is not it be more beneficial to update only one method if we replace the string based query building with an AST based approach in comparison to change different methods for different APIs?

**Comment by c0c0n3** [comment]
Hi @pooja1pathak :-)

> new query method but unable to get the perfect query.

Yea, I know. The code is pretty intertwined and there's no easy way to reuse single bits and pieces out of context. So if it's too hard to implement a separate query, rather add to the existing one. But please be extra careful, like go in with surgical gloves and scalpel, since the existing query method is QL's workhorse so whatever we do the existing semantics **must** stay the same after the change :-)

> Is not it be more beneficial to update only one method...

If we go down the AST road, then we'll have to rewrite both the reporter and translator from scratch, so all methods will have to go. My thinking is that having a separate query method for types a this stage would make it easier in the future to see what's going on in the code since it should be easier to understand that bit of functionality in isolation...but I suppose this is a bit of a moot point. So like I said earlier, don't waste your time on this if it's easier to modify the existing query method without any side effects then rather do that :-)

**Comment by pooja1pathak** [comment]
@c0c0n3 Thank you for your response :-) 
I would suggest to address the AST viewpoint in another issue. So, we can raise a new issue for separate query of each API and then we can investigate on that.
Regarding the current issue #119 we can proceed with existing query method.

**Comment by c0c0n3** [comment]
@pooja1pathak 

> address the AST viewpoint in another issue

Agreed! At the moment this is just an idea and I'm not even sure myself it's worth our while looking into this, but will open an issue if one day we decide to go ahead with it.

> Regarding the current issue #119 we can proceed with existing query method.

cool bananas, thanks!!!

**Comment by pooja1pathak** [comment]
As PR #293 is merged, we can close this issue.

**Comment by c0c0n3** [comment]
thanks for reminding me!
