### ISSUE TITLE
Make /v2/entities return available ids

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#162]
It may be useful if `/v2/entities` returned at least the ids of the available entities to further query for.

**Comment by pooja1pathak** [comment]
Hi @taliaga , I am working on this issue. Please assign it to me.

**Comment by chicco785** [comment]
hi @pooja1pathak 
performance wise, rather than using the `query` function in the translator, it may be easier and more performing to create a specific function.

1. you can use pagination (offset and limit) to return the list of tables, e.g.
`SELECT DISTINCT "table_name" FROM "doc"."md_ets_metadata" LIMIT 100;`
2. then you can use the list of tables to build a union query with pagination:
`SELECT entity_id, entity_type, max (time_index) time FROM "mtekz"."etdevice" GROUP BY entity_id, entity_type 
UNION ALL SELECT entity_id, entity_type, max (time_index) FROM "mtekz"."etstreetlight" GROUP BY entity_id, entity_type
 limit 100;`
3. in the result, it would be nice to return also entity_type and max index (see example above).
4. it would be nice to be able to filter by entity_type and time index.

**Comment by c0c0n3** [comment]
closed by #264.
