### ISSUE TITLE
Migrate data from STH-Comet to QuantumLeap

### ISSUE THREAD

**Issue by pooja1pathak** [smartsdk/ngsi-timeseries-api#180]
I am trying to migrate data from STH-Comet to QuantumLeap and access that data with QuantumLeap APIs. As both the GEs have different database and the structure of the data storage is different, is there any way to do this?

**Comment by chicco785** [comment]
@pooja1pathak we haven't planned any migration tool. An idea could be
1. Download as JSON the collections from mongo
1. Reformat the JSON (if needed) as proper NGSI for the QL /notify endpoint 
1. Send data entity by entity to the QL /notify endpoint (be careful with setting in the header the proper time index)

**Comment by pooja1pathak** [comment]
Hi @chicco785, Thank you for your response.
I am using the same approach to migrate data from STH to QL. 
I am writting code in JAVA to automate this task and I am facing some issue while connecting to docker container via code.
I am unable to connect to docker container of mongoDB.
In my environment STH and QL both are running as docker container.

Please guide me further.

**Comment by taliaga** [comment]
Hi @pooja1pathak,

How are you deploying your containers? Below some help assuming you're using the [docker-compose-dev.yml](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/docker/docker-compose-dev.yml)

If your code is also running in a container (ideal), make sure such container is [launched on the same docker network](https://docs.docker.com/engine/reference/run/#network-settings) where Mongo (and QL) is running. In this case you'll find the db at `mongo` host.

Otherwise, if you're running everything on your local host, make sure the MongoDB ports are exposed on your development localhost, like [this](https://github.com/smartsdk/ngsi-timeseries-api/blob/f004386e566eb855f5bb4e5b4df1023c1def2a5e/docker/docker-compose-dev.yml#L21). In this case you'll find the db at `localhost`.

**Comment by pooja1pathak** [comment]
Fixed in #196
