### ISSUE TITLE
Handle ql/v2 root endpoint

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#217]
The root endpoint (https://ql/v2/) should not error out, maybe present the api with the different options available

**Comment by taliaga** [comment]
maybe best solved together with https://github.com/smartsdk/ngsi-timeseries-api/issues/94

**Comment by iamarnavgarg** [comment]
Hi , I would like to work on this issue.
Thanks

**Comment by chicco785** [comment]
hi @iamarnavgarg you are welcome to contribute!
if you provide a short description of how you plan to handle it (it could be also through an initial pull request updating the [swagger doc](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/specification/quantumleap.yml)), we will provide you feedback before you start coding.

cheers

**Comment by ansh1221** [comment]
Hi @chicco785 ,

My approach would be as follows:
1. We will create a new file with api.py present at location /reporter. Here, we will return the list of it's available api's while calling `http://ql-url/v2/`
2. Moreover, we will add new path corresponding to `/v2/` in the `/specification/quantumleap.yml `file, so that it will call the api when we hit `http://ql-url/v2/` URL. 

Please let me know in case of any concerns.

**Comment by iamarnavgarg** [comment]
Hi @chicco785 ,

My approach would be as follows:

We will create a new file with api.py present at location /reporter. Here, we will return the list of it's available api's while calling http://ql-url/v2/
Moreover, we will add new path corresponding to /v2/ in the /specification/quantumleap.yml file, so that it will call the api when we hit http://ql-url/v2/ URL.
Please let me know in case of any concerns.

**Comment by chicco785** [comment]
hi @iamarnavgarg
Sounds good. I would also include a new test for the new endpoint.
