### ISSUE TITLE
First-time null values taken as object attributes

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#224]
**Is your feature request related to a problem? Please describe.**

When the first notification arrives with an attribute value of Null, QL creates a column for it of type null 

**Describe the solution you'd like**

In those cases, don't commit to a data type and simply ignore the attribute.

**Describe alternatives you've considered**

**Additional context**

**Comment by pooja1pathak** [comment]
Hi @taliaga @c0c0n3 ,
I want to contribute in this issue. 
Please confirm my below understanding:
1. Case 1: All the attributes have Null value.
2. Case 2: One of the attributes have Null value and all the others have valid values. 

For case 1:  No value will be stored neither will table be created.
For case 2: Table will be created for the valid attributes and attributes with Null values are ignored. No column for that value is created.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak thanks for volunteering :-)

This gets confusing for me too so I'll try to state the problem a bit more precisely below, mainly for my own benefit so I'll be able to understand what's going on a year from now :-)

Call `E = { e[1], ..., e[n] }` the set of entities being notified to QL (i.e. what gets POSTed to `/v2/notify`) and `T` the set of DB tables we have when QL gets the notification. Also let's say we've got a test function:

    known : Entity x Attr --> Bool
    known(e, a) = T  just in case ∃ t ∈ T for e.type and ∃ column t.a

Then for each attribute `a` of `e[k]` (`k = 1, ..., n`)

1. If `not known(e[k], a)` and `not has_value(e[k].a)` ([has_value](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/reporter/reporter.py#L57) as defined in the Reporter module), then do *not* store `a`. You can simply delete the attribute from the Python entity dictionary here.
2. In all other cases, i.e. when condition (1) is false, keep the attribute. Just leave it be, the existing code should take care of storing it in the DB.

The challenge here is to come up with an efficient implementation of that test function. We have a metadata table you can query. Ideally we should wrap all this in a transaction to avoid race conditions but given the current implementation of the `notify` endpoint, that's easier said than done. So if you agree I suggest we blissfully ignore race conditions---all that can happen anyway is that we won't store a "no-value" attribute we should've stored, not a big deal in my opinion.

For some more context see #241. The problem there is related but not the same.

**Comment by c0c0n3** [comment]
@pooja1pathak @chicco785 
After reviewing #298, I can't help thinking that maybe we shouldn't go down that road. Do we actually have cases of notifications in the wild where we get an attribute value of `"Null"` (i.e. a string containing the chars `N`, `u`, ...) as in

    { 
        "id": "nasty::1",
        "type": "Device",
        "state": { "type": "Text", "value": "Null" },
        "temp": { "type": "Number", "value": "Null" }
    }

My understanding is that this issue got raised because of entities like this instead

    { 
        "id": "nasty::1",
        "type": "Device",
        "state": { "type": "Text", "value": null },
        "temp": { "type": "Number", "value": null }
    }

Notice the JSON `null` value here as opposed to a string containing "Null" as word. The case of JSON `null`s should already be covered by PR #278 which fixed #209.

Going back to the first example up there, I reckon we can all agree we can safely ditch something like this

    "temp": { "type": "Number", "value": "Null" }

since the value here isn't even a number, but what about

    "state": { "type": "Text", "value": "Null" }

Looks suspicious and most likely an error but how can we tell for sure? After all the value (`"Null"`) is compatible with it's declared type (`Text`) and perhaps `"Null"` actually names a state the device can be in---e.g. it could stand for device not yet initialised, init error, etc.

**Comment by chicco785** [comment]
Hi,
to be honest i don't recall how this issue was born.

is there are test were we can see it occurring? then maybe there is a
problem in the old pr and related test.

a similar issue, that is for sure something to think about is "dropping"
attributes that cannot be cast to the proper attribute format,
so we save at least the other values and don't reject the full message.

**Comment by c0c0n3** [comment]
> don't recall how this issue was born.

Um, the plot thickens. I've got a faint recollection of Thomas explaining it to me and pointing the finger at JSON `null` but I never actually saw the culprit myself, so can't tell for sure. If my memory serves me well, it was some LORAWAN data he was struggling with.

> is there are test were we can see it occurring?

Not that I know. I couldn't find anything like that.

> "dropping" attributes that cannot be cast to the proper attribute format

Great idea! In fact, this is the second time you have it :-)) You asked me to open an issue a while back, see #241.

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 , @chicco785 

I have checked for the above, below is my observation:
**CASE-1:**
When we notify QL for an entity say Room with 2 attributes i.e., temperature and pressure as for the very first notification, temperature value is set null with type Number and pressure value is 15 of type Number. The notification successfully gets processed. 
**Entity is created in Crate DB as temperature with value "NULL" of type ```Number``` and pressure with value 15 of type Number.**

In second notification, temperature value is set 25 with type Number and pressure value null with type Number. This time also, Notification is successfully processed.
**Entity updated in Crate DB as temperature with value 25 of type ```Number```, pressure with value "NULL" and type Number.**

Now when I try to get entity for pressure and temperature using requests: ```/v2/entities/RoomTest1/attrs/pressure?aggrMethod=sum&aggrPeriod=hour``` and ```/v2/entities/RoomTest1/attrs/temperature?aggrMethod=sum&aggrPeriod=hour``` respectively. 
I get value 15 as response for pressure and 25 for temperature. This is as per expected result.
**This means the type of attribute is set to Number when first notification is received.**

**CASE-2:**
When we notify QL for an entity say Room with 2 attributes i.e., temperature and pressure as for the very first notification, temperature value is set null with type Number and pressure value is 15 of type Number. The notification successfully gets processed. 
**Entity is created in Crate DB as temperature with value "NULL" of type ```Number``` and pressure with value 15 of type Number.**

In second notification, temperature value is set 25 with type **```Text```** and pressure value null with type Number. This time also, Notification is successfully processed.
**Entity updated in Crate DB as temperature with value 25 of type ```Number```, pressure with value "NULL" and type Number.**

Now when I try to get entity for pressure and temperature using requests: ```/v2/entities/RoomTest1/attrs/pressure?aggrMethod=sum&aggrPeriod=hour``` and ```/v2/entities/RoomTest1/attrs/temperature?aggrMethod=sum&aggrPeriod=hour``` respectively. 
I get value 15 as response for pressure and 25 for temperature.
**This means the type of attribute is set to Number when first notification is received and is not updated after that.**

**CASE-3:**
When we notify QL for an entity say Room with 2 attributes i.e., temperature and pressure as for the very first notification, temperature value is set null without any type and pressure value is 15 of type Number. The notification successfully gets processed. 
**Entity is created in Crate DB as temperature with value "NULL" of type ```Text``` and pressure with value 15 of type number.**

In second notification, temperature value is set 25 with type Number and pressure value null with type Number. This time also, Notification is successfully processed.
**Entity updated in Crate DB as temperature with value 25 of type ```Text```, pressure with value "NULL" and type Number.**

Now when I try to get entity for pressure and temperature using requests: ```/v2/entities/RoomTest1/attrs/pressure?aggrMethod=sum&aggrPeriod=hour``` and ```/v2/entities/RoomTest1/attrs/temperature?aggrMethod=sum&aggrPeriod=hour``` respectively. 
**I get value 15 as response for pressure and ```No record found for temperature```.** 
It may be because temperature is saved as Text and it is not updated when we add Type as Number.

In my opinion if for any entity value is null and no Type is defined then we should ignore that attribute without committing to any type. If this suggestion looks good to you, I can work in that direction and update my PR.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak, thanks for testing those scenarios :-)

> CASE-1 ...
> type of attribute is set to Number when first notification is received.
> CASE-2 ...
> type of attribute is set to Number when first notification is received and is not updated after that.

Spot on! That's how notifications work at the moment. #241 explains in more detail what happens under the bonnet---see problem section.

> CASE-2 ...
> In second notification, temperature value is set 25 with type Text and pressure value null with type Number. This time also, Notification is successfully processed.

I reckon that's because of implicit type conversions. The temperature column got created numeric in the first notification and the temperature value in the second notification is the string `"25"` which happens to be convertible to the integer `25`.

> CASE-3 ...
> Entity is created in Crate DB as temperature with value "NULL" of type Text

Quantum Leap defaults attributes of unknown NGSI type to Text. Since an attribute DB column gets created the first time we see an attribute, if there's no NGSI type, the column winds up with a text type, I suppose.

> CASE-3 ...
> second notification, temperature value is set 25 with type Number... updated in Crate DB as temperature with value 25 of type Text

Implicit type conversions kicked in again I reckon.

> CASE-3 ...
> get entity for pressure and temperature... No record found for temperature

This is an instance of #296---single-table/one attribute scenario. Have a look at [this comment](https://github.com/smartsdk/ngsi-timeseries-api/issues/296#issuecomment-613033340) over there for the details.

**Comment by c0c0n3** [comment]
> In my opinion if for any entity value is null and no Type is defined then we should ignore that attribute without committing to any type.

I like your suggestion. Let's put a bit more flesh on the bones of this. I'm going to use the same notation defined in my [earlier comment](https://github.com/smartsdk/ngsi-timeseries-api/issues/224#issuecomment-605915939), please have a look there for the details.

So what we want is this. For each entity `e` and attribute `a`

    not known(e, a) and not has_value(e.a)  ===>  do not store a
    otherwise                               ===>  do nothing

I've already mentioned the challenge here is to come up with an *efficient* implementation of the `known` function. But come to think of it, we can get pretty much the same desired outcome if we just delete `a` from `e` when`has_value(e.a) = false` and there's no type, i.e. if the implementation is

    not has_value(e.a) and e.a.type is None  ===>  del e.a
    otherwise                                ===>  do nothing

and that happens after calling ` _filter_empty_entities`. (At some point we should reimplement all this using stream processing so that we don't loop through the entity array one gazillion times, but I'll leave that for another day :-)

With the above implementation if an attribute comes in for the first time with no value and no type, we just ignore it as you suggested. If the attribute exists already in the DB and it comes in with no value and no type, by deleting it, we won't change much: the net result will still be a DB `null` for that field in the corresponding entity row. If we happen to delete all attributes (except for entity ID and type which we should never touch), then the insert should still work fine in both of the above scenarios---famous last words :-)

There's a side-effect though. An attribute won't be "queryable" until such a time we get notified of an actual value or a typed null/none. Until that time, the client will get a `404` when trying to retrieve it, e.g.
`/v2/entities/RoomTest1/attrs/temperature`. So `404` won't necessarily mean Quantum Leap never got notified of that attribute, but rather: Quantum Leap hasn't yet seen a value for that attribute or a typed null. In part this is happening already, so I don't think this is actually a big deal?

**Comment by pooja1pathak** [comment]
Thank you for the detailed explaination :-)

I am writing a new function which will get called after ```_filter_empty_entities``` to filter no_value and no_type attributes from the entities, as suggested by you.

I'll update my PR once it is done.

**Comment by c0c0n3** [comment]
> Thank you for the detailed explaination :-)

Pleasure! Thank you for the detailed report and suggestion!

> I'll update my PR once it is done.

That's great, thanks a stack!

**Comment by pooja1pathak** [comment]
Hi @c0c0n3  I've updated my PR #298  as per our discussion.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak I've just merged your PR. Great stuff, thank you sooooo much!!
Closed by #298
