### ISSUE TITLE
Failing to run up docker containers via docker-compose

### ISSUE THREAD

**Issue by mtalhaf** [smartsdk/ngsi-timeseries-api#270]
While trying to run a local instance of quantum leap with all the other necessary tools via the  docker-compose provided, the quantum leap container fails with an error of "Failed to add operation for POST /v2/config", while the final error being "connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "reporter.reporter.config"! Import error was "No module named 'pytest'">"

**To Reproduce**
1. Download repository as zip
2. Navigate to docker folder
3. Run `docker-compose -f docker-compose-dev.yml up -d`

**Expected behavior**
All tools should run properly to be able to test quantum leap.

**Environment (please complete the following information):**
 - OS: Mac High Sierra 10.13.6

Find attached the logs form Quantum leap while running the docker-compose without the `-d `command

[Quantum-leap-error.txt](https://github.com/smartsdk/ngsi-timeseries-api/files/3793943/Quantum-leap-error.txt)

Any help with this is appreciated.

**Comment by c0c0n3** [comment]
Hi @mtalhaf, it looks like your problem could be that you didn't run `pipenv install` (installs Python env + deps) and `setup_dev_env.sh` (sets up vars you'll need to run docker compose files). Try this:
 
    $ cd wheres/you/extracted/ngsi-timeseries-api
    $ pipenv install
    $ sh setup_dev_env.sh
    $ cd dir/where/docker-compose/you/want/to/run/is
    $ docker-compose up -d

Let me know if that works for you :-)

**Comment by chicco785** [comment]
i think the point is which image has been used, if it is the one from the
docker hub repo,
there is surely a problem, a local one was used, I believe andrea is correct

**Comment by kernchen** [comment]
@chicco785, @c0c0n3,

Just writing, since I've been working on this with @mtalhaf together. We basically tried out QuantumLeap. I tried it out a bit earlier with this hash, that didn't have any issues:

sha256:d310ee076e91a60c857c9f49dee5524149d52b44afe763e9b8ac661f0f0de6bb

It's coming directly from Docker Hub. We've been using the same docker-compose-dev.yml file. While mine processed fine, it says "2 weeks ago". @mtalhaf is now having issues with latest.

Hope that helps.

**Comment by kernchen** [comment]
Maybe as an addition, would you recommend using 0.7.5 instead of latest?

**Comment by c0c0n3** [comment]
@mtalhaf @kernchen hi guys, like I said, did you try doing what I suggested? In particular the reason for running `setup_dev_env.sh` is that it also builds a local QL image that the docker compose files pick up later---see env vars in those docker compose files, which btw get set up when you run `setup_dev_env.sh`. Anyway, like I said earlier it looks like your problem is that `pytest` isn't there, which is why you should try running `pipenv install`. Long story short, please try what I suggested earlier :-) 

For the record, this works flawlessly on my Mac:

    $ git clone https://github.com/smartsdk/ngsi-timeseries-api.git
    $ cd ngsi-timeseries-api
    $ pipenv install
    $ sh setup_dev_env.sh
    $ cd docker/
    $ docker-compose -f docker-compose-dev.yml up -d
    $ docker-compose -f docker-compose-dev.yml logs
       (...hunky dory...)
    $ curl http://0.0.0.0:8668/v2/version
    {
        "version": "0.7.5"
    }

Again, shout if this still doesn't work for you, we'll be glad to help :-)

**Comment by c0c0n3** [comment]
@mtalhaf @kernchen hi again, are you running on Linux by any chance? Just got this Travis build error:

https://travis-ci.org/smartsdk/ngsi-timeseries-api/builds/605998561?utm_source=github_status&utm_medium=notification

on a Linux box which looks similar to yours. Will dig deeper...

**Comment by kernchen** [comment]
@c0c0n3 hi, we tried it on an AWA EC2 instance, but also locally on a Mac had issues. We now managed to get a running setup online, but with the actual 0.7.5, so I'll try to follow your steps in the previous posts on my Mac and see if this throws any errors and let you know.

**Comment by kernchen** [comment]
OK, seems at least locally on my Mac this doesn't produce any issues for me according to your previous provided steps.

**Comment by c0c0n3** [comment]
hi @kernchen, thanks for this. PR #271 implements a fix---what was broken is detailed in the comments to #269. As soon as we merge #271 into master you should be able to build and run the QuantumLeap image on any box, in particular on an EC2 instance. If you could please try again after we merge #271 and let us know if you still have any issues.

**Comment by chicco785** [comment]
#271 is merged and the build is successful
