### ISSUE TITLE
Document that when using crateDB backend 3D coordinates are not supported

### ISSUE THREAD

**Issue by Glagnar** [smartsdk/ngsi-timeseries-api#287]
**Describe the bug**
A valid GeoJson crashes the system.
Validation failed for location: Cannot cast {"coordinates"=[53.822510377, 2.485033098, 68], "type"='Point'} to type geo_shape]

Check chapter 9 of the RFC, it is valid to have altitude as a third parameter.
```
{"type": "Point", "coordinates": [lon, lat, alt]}
```

**To Reproduce**
1. Send this payload to '...'
2. See error

**Expected behavior**

**Environment (please complete the following information):**

**Additional context**

**Comment by chicco785** [comment]
Hi,
1. [crate](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#geo-shape) does not support 3D coordinates, so in the best case, the processor should strip the alt.
2. I suspect that some of the functions we use, such as the one to compute centroids, maybe become quite complex computationally.

In short, the only fix in the short term is stripping alt, if that is not going to be good for you, we welcome a pull request to solve the issue otherwise (maybe in timescale 3d support is available).

**Comment by Glagnar** [comment]
Thank you for the speedy reply, and I understand the problem. Here are my thoughts.
a) I honestly think it is a bad idea to truncate data without notifying the user, they may loose stuff. 
b) The user 'me' will find out very quickly if their data is not there, and may find out too late if you save part of the data.
c) Improve the error message, to indicate you know you do not support the RFT
d) Write somewhere in the docs that you do not support full NGSI ?

Thanks, I will remove the altitude in my payload to get data in.

**Comment by chicco785** [comment]
The error message reported is actually from cratedb, the internal processor is perfectly parsing geojson:
https://github.com/crate/crate/issues/8053

We will see how to improve error, by clarifying that the error is originated by the backend.

FYI, I checked and postgis supports 3D coordinates, which means also timescale does. Hopefully (haven't tested) this means that if you used timescale as backend, it should work. The draw back would be that we don't have (yet) query api for timescale.

At the time being, I think we will document that the crate backend does not support 3D coordinates.

**Comment by mechanomi** [comment]
we have a note about this now:

https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#geo-shape

see https://github.com/crate/crate/issues/8053 for the feature request, which will remain open and on our backlog for the time being

closing the issue

thanks! :)

**Comment by daminichopra** [comment]
Hi @chicco785 , I would like to work on this issue. Please assign me if no one is working on this issue. Thank you :)

**Comment by c0c0n3** [comment]
Hi @daminichopra, just assigned this to you. Thanks alot!

If you could please test what happens with the Timescale backend too. In principle the above example should work with Timescale, but we have to make sure. If it doesn't, then if you could please document that at the moment QL doesn't support 3D coords, regardless of which backend is used.

**Comment by daminichopra** [comment]
Hi @c0c0n3 , Extension [PostGIS](http://postgis.net/) can be installed alongside with [TimescaleDB](https://www.timescale.com/). PostGIS supports 3D points, which are created by [ST_MakePoint](https://postgis.net/docs/ST_MakePoint.html). In short TimescaleDB does support 3D coordinates whereas CrateDB does not support 3D coordinates which i have described in [PR](https://github.com/smartsdk/ngsi-timeseries-api/pull/340).
Please check the PR and if it looks good then Merge and close this [PR](https://github.com/smartsdk/ngsi-timeseries-api/pull/340). Thank you :)

**Comment by c0c0n3** [comment]
Hi @daminichopra thanks so much for this!
@Glagnar so it turns out Crate doesn't support 3D coords and now there's a mention of it in the manual---see #340 by @daminichopra. I reckon we can close this issue then. If you can't do without 3D, you may want to consider using QL with the Timescale backend + PostGIS extension, as @daminichopra points out. Our manual documents how to set up a QL backend made up by Postgres + Timescale + PostGIS. Keep in mind though that at the moment while you can safely use the QL API to insert data into Timescale, the query API still has some rough edges we'll smooth out for the upcoming `0.8` release---see #324.
