### ISSUE TITLE
Run TimescaleDB only 

### ISSUE THREAD

**Issue by DerLinne** [smartsdk/ngsi-timeseries-api#391]
**Is your feature request related to a problem? Please describe.**
We like to run QL with a TimescaleDB only Backend without Crate. Currently this seems to be not possible. When configuring only the TSDB Environment Parameters and setting the default backend to „timescale“ in the Quantum Leap Configuration, Crate is use additionally. Notifications fail in this case because Crate is tried to reach with default Server Name and this fails. 

**Describe the solution you'd like**
Additional Environment Variable(s) to explicitly configure which backend should be active.

**Describe alternatives you've considered**
I tried to set all (for me known) setting, but Crate keeps active.

**Comment by DerLinne** [comment]
In the meantime I figured out, that Timescale is only useable for other Clients than default. So now it is running, but the documentation does not really explain how:

Examples:
- Wrong environment variables names in the documentation (PG instead of POSTGRES_DB as prefix)
- Missing environment variables names in the documentation (LOGLEVEL)
- Missleading Environment Variables Names (QL_DEFAULT_DB) - I would expect that this default is also valid for the default service

So, it is running now for me for special services - but an updated Documentation would really help

**Comment by c0c0n3** [comment]
@DerLinne thank you for getting in touch!

> We like to run QL with a TimescaleDB only Backend without Crate. Currently this seems to be not possible. 

You should be able to do that with a YAML config file where you set `default-backend: Timescale`, details over here:

- https://quantumleap.readthedocs.io/en/latest/admin/configuration/

> Additional Environment Variable(s) to explicitly configure which backend should be active.

Well, we do have one called `QL_DEFAULT_DB` but we've only been using that internally since it may change in the future when we consolidate configuration. Feel free to use it in the meantime if that suits you.

 > documentation does not really explain how:

Perhaps the explanation over here isn't clear enough?

- https://quantumleap.readthedocs.io/en/latest/admin/configuration/

We welcome suggestions for improvement!

> Wrong environment variables names in the documentation (PG instead of POSTGRES_DB as prefix)

Uh? Where is that? I think the "official" env vars have a prefix of `POSTGRES_DB` **not** `PG`? This is the page I'm talking about:

- https://quantumleap.readthedocs.io/en/latest/admin/configuration/

> Missleading Environment Variables Names (QL_DEFAULT_DB)

Like I said earlier, this variable hasn't yet made it to the official docs even though we've been using internally so we weren't expecting anyone else to use it...

> updated Documentation would really help

Sure. If you have any other concerns or suggestions we'll try our best to improve the docs. Even better, you could open a PR to rework some of the sections you think aren't clear enough and we'll gladly review it :-)

**Comment by chicco785** [comment]
@DerLinne can you let us know which documentation you are referring to? probably there is some old pointer around... as reported by @c0c0n3 the only missing documented variable is `QL_DEFAULT_DB` which is not official yet, and all other elements are included and up-to-date

**Comment by DerLinne** [comment]
Hi!

Sorry for the late reply - I did not manage to answer ealier.

I think I started from here: https://quantumleap.readthedocs.io/en/latest/admin/timescale/. The variables are fixed there.

But for example I did not find a mention of the DEBUG ENV-Variable - but I found it in the code.

Last topic:

Yes I configured the default-backend: Timescale. I think this works If you specify any Fiware-Service. But if you do not provide this Header in the Requests, a fallback to Crate takes place.

**Comment by c0c0n3** [comment]
Hi @DerLinne :-)

> Sorry for the late reply

No need to apologise :-)

>  mention of the DEBUG ENV-Variable - but I found it in the code.

There's a `LOGLEVEL` env var (I think this is what you bumped into?) but it's documented one level up from the Timescale section you were looking at initially:

* https://quantumleap.readthedocs.io/en/latest/admin/configuration/

`admin/configuration/` lists every env var known to man, whereas the Timescale section documents in more detail those specific to the Timescale backend.

> Yes I configured the default-backend: Timescale. I think this works If you specify any Fiware-Service. But if you do not provide this Header in the Requests, a fallback to Crate takes place.

Yep, you hit the nail on the head. This is a genuine bug we'll have to squash. I opened a separate issue (#404) for that since we've been focussing on docs in this issue thread. Speaking of which, @DerLinne if you have no more comments about docs, I'd close this issue. That okay?

**Comment by DerLinne** [comment]
> Yep, you hit the nail on the head. This is a genuine bug we'll have to squash. I opened a separate issue (#404) for that since we've been focussing on docs in this issue thread. Speaking of which, @DerLinne if you have no more comments about docs, I'd close this issue. That okay?

Yes, thats ok for me - thanks!
