### ISSUE TITLE
Query API more often than once per second

### ISSUE THREAD

**Issue by SBlechmann** [smartsdk/ngsi-timeseries-api#418]
**Describe the bug**
I'm not sure whether this has to do with the "high load" performance issues.. but my use case demands to get, e.g. the last 10 values of an attribute more often than once per second. 
Let's say my device sends values every 0.1 seconds (and that is actually a slow device). Let's assume I need to query the last 10 values of that device (ofc an attribute of that device) every 0.5 seconds.
So If I query lastN=10 values for the first time (t0) I get the correct (I assume) last 10 values. For the second query (t0+0.5s) that I get the same 10 values.

**To Reproduce**
As described:
Push a new value for an attribute every 0.1 seconds to orion (subscription for QL already created) - well, I used a complete chain from MQTT broker to QL but that should not matter since all the values reach cratedb.
While the device sends data continiously query QL with lastN=10 (or whatever number) more often than once a second, e.g. every 0.5s.

**Expected behavior**
That QL throws the actual last 10 values. In this case this would be the last 5 values of the query before plus 5 new values.

**Environment (please complete the following information):**
OS: Orion:2.5.2, mongoDB:4.2.2, QL:fix-256 and crateDB:4.2.2 run in docker on Ubuntu 18
A real device or a script as device simulator to send data; in my case a python file.
Some script that queries QL; in my case a python file.

**Additional context**

As the last time every help is much appreciated :)

**Comment by chicco785** [comment]
few hints: 
1) are you sure orion is sending notifications for all received data? be aware that if an update comes before the notification is queued, it will actually send only the new update.
2) did you try to query after more than 0.5s and see if the data were updated correctly? there is a processing time to store data, ql is not meant to be a real time api. the real time api is context broker :)

**Comment by c0c0n3** [comment]
@SBlechmann thank you so much for the detailed report!

also, w/r/t the comments above:

#### Notification throttling
When you create an NGSI notification there's an optional `throttling` field that lets you specify a notification interval in seconds. If my memory serves me well, Orion defaults it to 1 second. In practice this may result in some updates being lost in cyberspace---e.g. if you send 10 entity updates to Orion within 1 second, not all 10 of them might get notified to QuantumLeap. Can do a GET on`http://your-orion:1026/v2/subscriptions` and tell us what's the value of the `throttling` field in your QuantumLeap subscription?

#### Doing real-time
I don't think it's a good idea to use QuantumLeap for real-time processing and the whole FiWare stack for that matter, but of course YMMV. By [real-time](https://en.wikipedia.org/wiki/Real-time_computing) I mean the ability of a system to satisfy time constraints. If your system **must** meet processing deadlines (e.g. get an accurate query result **every 0.5 seconds**) then REST microservices aren't your friend, IMO :-)

#### Reproducing the bug
I tried to reproduce by taking a shortcut, by POSTing entities directly to QuantumLeap, bypassing Orion, but I had no luck reproducing the issue---yep, I suppose I took too much of a shortcut :-)

> I used a complete chain from MQTT broker to QL but that should not matter since all the values reach cratedb

I'm assuming you checked all your values are in the QuantumLeap entity table, e.g. `SELECT count(*) FROM ...`. Can you confirm that? The reason why I'm asking is that I'm trying to narrow this issue down. As it stands now it could be either a bug in QuantumLeap's query subsystem (if all entity values are in Crate) or it could be a problem with notifications, either Orion or QuantumLeap---see #416, even though I never experienced myself any data loss with the kind of load you're using. Either way we'll look into this :-)

**Comment by SBlechmann** [comment]
hey there, thanks for your questions :) 

regarding @chicco785 's comment:
I just reset everything, so here's what I got:
I sent 27 values in a simple loop from 1 to X, increasing by 1, one value every 0.5s. Orion shows 28 sent notifications (since 1 is created at the creation of the subscription that's the correct amount). 
When I query QL for those values, they are all there and displayed correctly ordered by time_index. 
In parallel to the data stream I queries QL's api also every 0.5s and here's what I got:
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:50.133'], 'values': [2.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:50.133'], 'values': [2.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:51.140'], 'values': [4.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:51.140'], 'values': [4.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:52.141'], 'values': [6.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:53.172'], 'values': [8.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:53.172'], 'values': [8.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:54.178'], 'values': [10.0]}
{'attrName': 'presentValue', 'entityId': 'urn:ngsi-ld:Sensor:Temperature:001', 'index': ['2021-01-20T18:24:54.178'], 'values': [10.0]}

Querrying Orion in parallel gives me the correct values.

Could you please explain your 2nd point? I don't understand. 

Regarding @c0c0n3 's comment:
Throttling is set to 0 - seems to work since all the data is correctly stored in crate.

Mhm.. so QL seems to be slower in this matter? But both (fiware in general) are not suupposed to serve real time applications / under high frequencies? I guess they are out of the question for electric use cases then? 

I hope I didn't forget anything and my data helps in this matter :)

**Comment by SBlechmann** [comment]
I actually forgot something.
So if querrying crate I get the same results as querrying QL. 

And I guess for time sensitive use cases the data should be grabbed from e.g. the MQTT broker directly then?

**Comment by chicco785** [comment]
@SBlechmann context broker is the real time component of FIWARE architecture.

QuantumLeap is a Timeseries API that stores values forwarded by the Context Broker, and due to the nature of its backends as well, there is always some synch latency between the data writing and the time the data is available for reading.

In first instance you have QL takes around 80 msec to process a single message (on my machine) and store it in the database. Especially in the case of crate, indexing may take a bit, so this means that there is additional latency between when the a message is stored in crate, and when it is actually available for querying. In case of distributed deployment this can take even more because QL writes on Crate node A, first the data is indexed in node A, and then replicated on node B. So if you issue a query right after writing a message and QL picks node B, probability to find the data you just pushed is even lower.

Also, fast data indexing in the database behind QL largely depend on its configuration.

Bottomline: 
- real time reading? Orion
- long term historical data persistency? QuantumLeap

**Comment by c0c0n3** [comment]
@SBlechmann thanks so much for the analysis and time you put into this, it really helps!

> But both (fiware in general) are not suupposed to serve real time applications / under high frequencies?

It depends on what your definition of real time is and how high is a high frequency in your case :-) In general, I reckon the whole FiWare architecture was built more with extensibility, ease of use and openness in mind than high performance. Witness the extensive use of HTTP, JSON, microservices, etc. none of which are really a good option for high performance computing. As for real time, if we took Wikipedia's definition of real time

>  software systems subject to a "real-time constraint", for example from event to system response. Real-time programs must guarantee response within specified time constraints, often referred to as "deadlines".

then my conclusion would be: **FiWare is not suitable for real time applications**. In general, microservices architecture are ill suited for real time applications since there's no way you can guarantee any deadline will be met---e.g. think how the proliferation of networked processes required to carry out a task affects latency.

> I guess they are out of the question for electric use cases then?

It depends. If you don't have strict real time requirements, then FiWare could well be an option. I would test **at scale** though since things will likely be very different than the happy laptop scenario the moment you have hundreds of devices pumping data through agents, context broker, etc. 

> I guess for time sensitive use cases the data should be grabbed from e.g. the MQTT broker directly then?

That would definitely help performance as well as **batching**.

**Comment by SBlechmann** [comment]
All right then.
Then the application needs to take care of some kind of stash itself, thanks 👍 that's already a good output of this discussion :)

I will conduct some further "performance tests" in regards to lots of devices sending data then with a clustered setup soon.

**Comment by c0c0n3** [comment]
@SBlechmann

> I will conduct some further "performance tests" in regards to lots of devices sending data then with a clustered setup soon.

Cool, good idea! There's a couple of things I'd mention based on our experience running FiWare stacks in a cluster just in case. In general, you should be able to get good performance out of the box---some components like Orion can handle loads of requests per second without a glitch. Like I said **hard** real time may not be FiWare's forte but you can still get **very good** performance out of a FiWare stack which brings me to the next point. Cluster configuration, infrastructure (e.g. network) and container orchestration tuning (e.g. K8s) can have a huge impact on how much performance you'll be able to squeeze out of your FiWare stack. I've experienced myself situations where I initially thought FiWare was the bottleneck meanwhile my cluster configuration was preventing containers from being scheduled properly. (D'oh! Yea, I'm dumb that way.)
