### ISSUE TITLE
[QUERY] Integration with InfluxDB

### ISSUE THREAD

**Issue by Racso93** [smartsdk/ngsi-timeseries-api#91]
Hello!

I have seen that there is the possibility of adding other databases, such as InfluxDB, and we wanted to know if you have implemented the integration with that database or in what state that possible implementation is.

A greeting.

**Comment by taliaga** [comment]
Hi,

During the first months of the project we did some tests with `CrateDB`, `InfluxDB` and `RethinkDB`, just as a proof of concept we developed a oversimplified translator for each. You can still find some remaining in the `translators` folder. The Influx translator deals with entities a bit differently, as it has to work with the concept of `measurements`.

It'd be possible to work on Influx's translator to catch up with the development done for the Crate one, but it'd take some effort which is not in our roadmap for now.

**Comment by chicco785** [comment]
The rational to invest on CrateDB are as follows:
- InfluxDB does not support natively geo-data-type, which means that to cover queries related to that, we will have to introduce a layer in the API, to process all entities there.
- InfluxDB (in the open source version) does not support HA configuration, limiting its usage in a production environment (unless you buy the enterprise license, which would not be anymore compatible with the ideals of FIWARE community)

**Comment by Racso93** [comment]
Thank you very much for your quick response and the information.

I'm glad to know that the decision to choose CrateDB was after a study of the rest.

Greetings.

**Comment by jmsbernabeu** [comment]
Hi, 
Now I have a problem with crate-datasource plugin for grafana. This plugin has removed from the official grafana plugins list. How can install this plugin manually?
Thanks

**Comment by taliaga** [comment]
Hi @jmsbernabeu , please don't hesitate to create new issues to discuss different problems. Otherwise this will not be visible to others.

Back to your question, we suggest you try the postgresql datasource plugin instead ([docs updated recently](https://quantumleap.readthedocs.io/en/latest/admin/grafana/#configuring-the-datasource)) because crate has deprecated the crate datasource plugin. We'll be migrating our usecases to postgres datasource plugin as well. If you still need to use the old plugin in the mean time, the overall idea is that you'll have to clone [datasource code](https://github.com/raintank/crate-datasource) and place it in `/var/lib/grafana/plugins` and probably activate it in the config file. Have a look at the grafana plugin installation docs for the details.
