### ISSUE TITLE
/version should be at root of API

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#94]
The basepath of the specification is set to `/v2`, but ideally `/version` would be better than `/v2/version`.

**Comment by daminichopra** [comment]
Hi @taliaga , I am working on this issue and just wanted to confirm my approach that I have removed basePath from quantumleap.yml file and added /v2 as prefix in other api e.g. for /config I have done /v2/config. 

Please confirm my approach so that i can raise PR.

**Comment by chicco785** [comment]
hi @daminichopra i would synch with PR #255 
check the discussion there, and let's either combine the PR, or build your PR on top of PR #255.

**Comment by chicco785** [comment]
hi @ddaminichopra PR #255 was merged
I would then proceed as follow:
- move `/v2/version`,  `/v2/config`,  `/v2/health` to root in the swagger [specs](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/specification/quantumleap.yml)
- remove those paths from the api [endpoint] (https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/reporter/api.py)
- change the test for api `/v2` so that these paths are not included in the return messages. see [here](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/reporter/tests/test_api.py)

thx
