### ISSUE TITLE
Issues with IndexArray in API specification

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#97]
https://github.com/smartsdk/ngsi-timeseries-api/blob/363450fb3ced2c1597b36342f0e96dc8797f8a61/specification/quantumleap.yml#L74

**Comment by taliaga** [comment]
It was specified as "ISO" format. I've improved a bit the description now in (https://github.com/smartsdk/ngsi-timeseries-api/pull/95/commits/47356901b06a550b1f1ac7cdeb86abcd99cfbeb1). But let's use this issue to consider these two things for this attribute.

[ ] - Include time-zone info in the response if it was present in the input.
[ ] - API says that if input was milliseconds, response would be as well, but this is not implemented.

**Comment by chicco785** [comment]
* I think keeping input in msec it's too complex. let me explain, suppose that you have two systems contributing the same "entity", one use msec the other iso format. how can you compare?
* I propose to have a way to define the default timezone and that all input data are set to that (which means they are converted to that if needed).

**Comment by taliaga** [comment]
Commenting on the questions above, comparing would still be possible because supporting the two just means you accept them as input, but in the backend both as stored in the same format (so they are comparable).

IMO timezones are an issue the user should be caring about, QL of course will never have to change the meaning of that. This mean, the user should know which timezone its index is at nofitication time, then the response must preserve the same (if there was no time index input then we say QL uses UTC).

We've mentioned in https://github.com/smartsdk/ngsi-timeseries-api/pull/161 that for now we'll support only ISO format for time index in the notifications. That's for the time index in the INPUT,  which is not an array, just one value. 

Now, for the output (the arrays QL returns) we're using millis for practical reasons (the verbosity of ISO is high if you handle several points and you already know what time you're talking about).
 
This github issue should then take care of: checking there's no timezone violation in the responses, and whether it's OK not to support millis in the input (this depends on use-cases I guess.)
